# Build stage
FROM node:21.7.2 AS build

WORKDIR /frontend

# Copy the source files into the image
COPY . .

# Install dependencies and build
RUN yarn install && yarn build

# Production stage
FROM nginx:alpine

# Copy the build files to Nginx
COPY --from=build /frontend/dist /usr/share/nginx/html

# Copy custom Nginx configuration
RUN rm /etc/nginx/conf.d/default.conf
COPY nginx.conf /etc/nginx/conf.d

# Expose port 80
EXPOSE 80

# Start Nginx
CMD ["nginx", "-g", "daemon off;"]